site_name: alakazam
site_url: https://alakazam.readthedocs.io
site_favicon: img/favicon.ico
repo_url: https://bitbucket.org/kleinstein/alakazam
edit_uri: src/master/docs/
theme:
  name: readthedocs
  navigation_depth: 2
  collapse_navigation: False
  sticky_navigation: False
  locale: en
  titles_only: False
  analytics:
    gtag: G-BDGVJ44VYF
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      baselevel: 1
      toc_depth: 1-4
      permalink: True
docs_dir: docs
nav:
  - 'Immcantation Portal': https://immcantation.readthedocs.io/
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/alakazam.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'How to read and write files': vignettes/Files-Vignette.md
    - 'Basic gene usage analysis': vignettes/GeneUsage-Vignette.md
    - 'Amino acid physicochemical property analysis': vignettes/AminoAcids-Vignette.md
    - 'Analysis of clonal abundance and diversity': vignettes/Diversity-Vignette.md
    - 'Reconstruction of Ig lineage trees': vignettes/Lineage-Vignette.md
    - 'Topology analysis of lineage trees': vignettes/Topology-Vignette.md
    - 'Using sequencing quality scores': vignettes/Fastq-Vignette.md
  - 'Help Topics':
    - 'File I/O':
      - topics/readChangeoDb.md
      - topics/writeChangeoDb.md
      - topics/readIgphyml.md
      - topics/combineIgphyml.md
      - topics/readFastqDb.md
    - 'Sequence Cleaning and Manipulation':
      - topics/collapseDuplicates.md
      - topics/maskSeqEnds.md
      - topics/maskSeqGaps.md
      - topics/padSeqEnds.md
      - topics/translateDNA.md
      - topics/isValidAASeq.md
      - topics/getPositionQuality.md
      - topics/maskPositionsByQuality.md
      - topics/junctionAlignment.md
    - 'Lineage Reconstruction':
      - topics/buildPhylipLineage.md
      - topics/graphToPhylo.md
      - topics/phyloToGraph.md
      - topics/makeChangeoClone.md
      - topics/ChangeoClone-class.md
    - 'Lineage Topology Analysis':
      - topics/getMRCA.md
      - topics/getPathLengths.md
      - topics/permuteLabels.md
      - topics/summarizeSubtrees.md
      - topics/tableEdges.md
      - topics/testEdges.md
      - topics/testMRCA.md
      - topics/plotEdgeTest.md
      - topics/plotMRCATest.md
      - topics/plotSubtrees.md
      - topics/EdgeTest-class.md
      - topics/MRCATest-class.md
    - 'Diversity Analysis':
      - topics/calcCoverage.md
      - topics/calcDiversity.md
      - topics/countClones.md
      - topics/estimateAbundance.md
      - topics/alphaDiversity.md
      - topics/plotAbundanceCurve.md
      - topics/plotDiversityCurve.md
      - topics/plotDiversityTest.md
      - topics/AbundanceCurve-class.md
      - topics/DiversityCurve-class.md
    - 'Ig and TCR Sequence Annotation':
      - topics/countGenes.md
      - topics/sortGenes.md
      - topics/groupGenes.md
      - topics/getSegment.md
      - topics/extractVRegion.md
    - 'Sequence Distance Calculation':
      - topics/getAAMatrix.md
      - topics/getDNAMatrix.md
      - topics/seqDist.md
      - topics/seqEqual.md
      - topics/pairwiseDist.md
      - topics/pairwiseEqual.md
      - topics/nonsquareDist.md
    - 'Amino Acid Propertes':
      - topics/aminoAcidProperties.md
      - topics/countPatterns.md
      - topics/aliphatic.md
      - topics/bulk.md
      - topics/charge.md
      - topics/gravy.md
      - topics/polar.md
    - 'Miscellaneous':
      - topics/baseTheme.md
      - topics/checkColumns.md
      - topics/cpuCount.md
      - topics/gridPlot.md
      - topics/makeTempDir.md
      - topics/progressBar.md
      - topics/stoufferMeta.md
      - topics/translateStrings.md
    - 'Data and Constants':
      - topics/ExampleDb.md
      - topics/ExampleDbChangeo.md
      - topics/Example10x.md
      - topics/ExampleTrees.md
      - topics/SingleDb.md
      - topics/ABBREV_AA.md
      - topics/IUPAC_CODES.md
      - topics/DEFAULT_COLORS.md
      - topics/IMGT_REGIONS.md
    - 'Deprecated':
      - topics/rarefyDiversity.md
      - topics/testDiversity.md
